plugins:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rake

AllCops:
  NewCops: enable # Enable all new cops by default
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'bin/**/*'

Style/Documentation:
  Enabled: false # Disable documentation requirement

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Rails/SkipsModelValidations:
  Enabled: false

Layout/LineLength:
  Max: 120

Naming/FileName:
  Exclude:
    - 'config/environments/*'
    - 'config/initializers/*'

Style/FrozenStringLiteralComment:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Rails/FilePath:
  Enabled: false
