services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD:
      POSTGRES_DB: klarbits_development
    ports:
      - "5432:5432"

  server:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3637 -b '0.0.0.0'"
    volumes:
      - .:/app
    ports:
      - "3637:3637"
    depends_on:
      - db
    environment:
      RAILS_MAX_THREADS: 5
      DATABASE_URL:
      POSTGRES_PASSWORD:
      DEVISE_JWT_SECRET_KEY:
      DOMAIN:
      DOMAIN_HOST:
      DOMAIN_PORT:

volumes:
  postgres_data:
  # bundle_cache:

