services:
  db:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: klarbits_development
    ports:
      - "5432:5432"

  server:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3003 -b '0.0.0.0'"
    volumes:
      - .:/app
      # - bundle_cache:/usr/local/bundle
    ports:
      - "3003:3003"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/klarbits_development
      RAILS_ENV: development
      RAILS_MAX_THREADS: 5
      # DEVISE_JWT_SECRET_KEY: ${DEVISE_JWT_SECRET_KEY}
      # GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      # GOOGLE_CLIENT_SECRET: ${GOOGLE_CLIENT_SECRET}

volumes:
  postgres_data:
  # bundle_cache:

