default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: klarbits_development
  url: <%= ENV["DATABASE_URL"] || "postgres://postgres:#{ENV['POSTGRES_PASSWORD']}@db:5432/klarbits_development" %>

test:
  <<: *default
  database: klarbits_test
  url: <%= ENV["TEST_DATABASE_URL"] || "postgres://postgres:#{ENV['POSTGRES_PASSWORD']}@db:5432/klarbits_test" %>

production:
  <<: *default
  database: klarbits_production
  url: <%= ENV["DATABASE_URL"] || "postgres://postgres:#{ENV['POSTGRES_PASSWORD']}@db:5432/klarbits_production" %>